site_name: Comatose
nav:
    - Story:
        - Chapter 1: chap1.md
        - Chapter 2: chap2.md
        - Chapter 3: chap3.md
        - Chapter 4: chap4.md
        - Chapter 5: chap5.md
        - Chapter 6: chap6.md
theme: 
    name: readthedocs
    titles_only: true
extra_css:
    - css/custom.css
