site_name: Comatose
nav:
    - Meta:
        - Home: index.md
        - Glossary: glossary.md
        - Projects: projects.md
        - Survey: "https://docs.google.com/forms/d/e/1FAIpQLSemjv1OPh7DzZj4kYXG5EsBx-ZADeGRU9DYp_-g9kKkR3-u8w/viewform"
    - Discovery Arc:
        - Chapter 1: chap1.md
        - Chapter 2: chap2.md
        - Chapter 3: chap3.md
        - Chapter 4: chap4.md
        - Chapter 5: chap5.md
        - Chapter 6: chap6.md
        - Chapter 7: chap7.md
        - Chapter 8: chap8.md
        - Chapter 9: chap9.md
theme:
    name: readthedocs
extra_css: [css/custom.css]
